# Generated by Django 2.2.2 on 2019-06-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('blade_material', models.CharField(max_length=255)),
                ('hardness', models.CharField(max_length=10)),
                ('handle_material', models.CharField(max_length=255)),
                ('lock', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('blade_length', models.FloatField()),
                ('full_length', models.FloatField()),
                ('blade_thickness', models.FloatField()),
                ('weight', models.FloatField()),
                ('producer', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Knife',
        ),
    ]
