# Generated by Django 2.2.2 on 2019-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0003_auto_20190610_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='img'),
        ),
    ]
